### ISSUE TITLE
Use Nuxt instead of Hyperapp

### ISSUE THREAD

**Issue by sr229** [Sayo-nika/Sayonika#2]
According to @Ovyerus, it should be easier to use Vue since it's a more established platform, plus it's easy to use Vue for our use case since we came from a pure HTML background (and Angular/React sucks).

# Todo

- [x] Nuxt rewrite - Client
- [x] handle foreachs for cards
- [x] die inside I guess

**Comment by sr229** [comment]
Conversion complete. Closing.
